# -*- coding: utf-8 -*-
"""Breast Cancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16j-aNVGWUy9E_aX-eDwyCsJUdSRbpjPI
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Load Dataset
df = pd.read_excel("Covid_Data.csv.xlsx")

# Missing Values
df["age"].fillna(df["age"].median(), inplace=True)
df["Blood O2 Level in Percentage"].fillna(
    df["Blood O2 Level in Percentage"].median(),
    inplace=True
)

# Encoding
df["body_temperature"] = df["body_temperature"].map({
    "Normal":0,
    "Moderate":1,
    "High":2
})

df["chronic_disease"] = df["chronic_disease"].map({
    "No":0,
    "Yes":1
})
df["chronic_disease"].fillna(0, inplace=True) # Fill NaN after encoding

df["breathing_issue"] = df["breathing_issue"].map({
    "No":0,
    "Yes":1
})
df["breathing_issue"].fillna(0, inplace=True) # Fill NaN after encoding

df["Needed Hospitalization"] = df["Needed Hospitalization"].map({
    "No":0,
    "Yes":1
})

# Features and Target
X = df.drop("Needed Hospitalization", axis=1)
y = df["Needed Hospitalization"]

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# Scaling
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Logistic Regression
classifier = LogisticRegression(random_state=42)

classifier.fit(X_train, y_train)

# Prediction
y_pred = classifier.predict(X_test)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix")
print(cm)

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# Report
print(classification_report(y_test, y_pred))