# -*- coding: utf-8 -*-
"""IPL_Capstone_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EXMXuvxftaB3mAXWAnJCWZkuG1dT0C0i
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df= pd.read_csv('IPL.csv')
df.head()

df.info()

print(f"your rows are {df.shape[0]}, and columns are {df.shape[1]}")

df.isnull().sum()

"""**Which team won the most matches?**"""

match_wins = df['match_winner'].value_counts()
sns.barplot(y= match_wins.index, x= match_wins.values, palette='viridis')
plt.title('Most match wins by team')
plt.xlabel('Wins')
plt.ylabel('Team')

"""**TOSS DECISION**"""

sns.countplot(x = df['toss_decision'],palette='rainbow')
plt.title('Toss Decision Count')

"""**Toss Winner vs Match Winner**"""

count = df[df['toss_winner']== df['match_winner']]['match_id'].count()
count

count = df[df['toss_winner'] == df['match_winner']]['match_id'].count()
percentage = (count*100)/df.shape[0]
percentage.round(2)

"""**How do teams win? (Runs vs Wickets)**"""

sns.countplot(x = df['won_by'])
plt.title("won By ")

"""**Key Player Performances**"""

count = df['player_of_the_match'].value_counts().head(10)
sns.barplot(x = count.values,y = count.index,palette='mako')
plt.title("Top 10 Player od the match")

"""**Top Scorers**"""

df['top_scorer'].head(5)

high = df.groupby('top_scorer')['highscore'].sum()
high

high = df.groupby('top_scorer')['highscore'].sum().sort_values(ascending=False).head(5)
high.plot(kind = 'barh')

"""**Best Bowling Figures**"""

df.head()

df['best_bowling_figure'].head(5)

df['best_bowling_figure'] = df['best_bowling_figure'].apply(lambda x : x.split('--')[0])
df['best_bowling_figure'] = df['best_bowling_figure'].astype(int)
top_bowlers = df.groupby('best_bowling')['best_bowling_figure'].sum().sort_values(ascending=False).head(10)
top_bowlers_df = top_bowlers.reset_index()
top_bowlers_df.columns = ['bowler', 'total_best_figures']

sns.barplot(data=top_bowlers_df, y='bowler', x='total_best_figures', palette='viridis')

"""**Most Matches Played by Venue**"""

venue_count = df['venue'].value_counts()
sns.barplot(y = venue_count.index,x = venue_count.values,palette='rainbow')

sns.countplot(data=df, y='stage', order=df['stage'].value_counts().index, palette='plasma')
plt.title('Match Stages in IPL 2022')
plt.show()

""": Who won the highest margin by runs?"""

df[df['won_by']== 'Runs'].sort_values(by = 'margin',ascending=False).head(1)[['match_winner','margin']]

"""Which player had the highest individual score?"""

df[df['highscore'] == df['highscore'].max()][['top_scorer','highscore']]

"""Which bowler had the best bowling figures?"""

df[df['best_bowling_figure'] == df['best_bowling_figure'].max()][['best_bowling','best_bowling_figure']]